### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by diezep** [Adventures-In/on_user_creation_microservice#1]
The links provided in Readme are broken
<img width="849" alt="image" src="https://user-images.githubusercontent.com/38699812/221371496-88ad79e0-647f-4e13-99b9-25a21efbe33c.png">

**Comment by nickmeinhold** [comment]
Looks like the Notion pages weren't public any more. I'm not sure how that happened, maybe when I moved stuff around. I just set them to public again, can you access them now?

**Comment by diezep** [comment]
No, still broken
Thanks

**Comment by nickmeinhold** [comment]
Oh man, sorry about that, I realise now I need to copy a different URL from Notion after making the page public. 

I believe I've fixed it properly now, I opened in Incognito and seems all good... is it working for you now?

**Comment by diezep** [comment]
Yes, thank you @nickmeinhold ! :)
